Description of gaussian_correlation
gaussian_correlation
PURPOSE
GAUSSIAN_CORRELATION Gaussian Kernel at all shifts, i.e. kernel correlation.
SYNOPSIS
function kf = gaussian_correlation(xf, yf, sigma)
DESCRIPTION
GAUSSIAN_CORRELATION Gaussian Kernel at all shifts, i.e. kernel correlation.
   Evaluates a Gaussian kernel with bandwidth SIGMA for all relative
   shifts between input images X and Y, which must both be MxN. They must
   also be periodic (ie., pre-processed with a cosine window). The result
   is an MxN map of responses.
   Inputs and output are all in the Fourier domain.
   See also MAXRESPONSEDSKCF, MAXRESPONSEDEPTHWEIGHTDSKCF,
   MODELUPDATEDSKCF, LINEAR_CORRELATION, POLYNOMIAL_CORRELATION,
   This function has been inserted in the DS-KCF matlab library from the
   KCF library released by
   Joao F. Henriques, 2014
   http://www.isr.uc.pt/~henriques/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
maxResponseDSKCF MAXRESPONSEDSKCF function for calculating the DSKCF response
maxResponseDepthWeightDSKCF MAXRESPONSEDEPTHWEIGHTDSKCF function for calculating the DSKCF response %
modelUpdateDSKCF MODELUPDATEDSKCF function for updating the DSKCF model %
SOURCE CODE
function kf = gaussian_correlation(xf, yf, sigma)
%GAUSSIAN_CORRELATION Gaussian Kernel at all shifts, i.e. kernel correlation.
%   Evaluates a Gaussian kernel with bandwidth SIGMA for all relative
%   shifts between input images X and Y, which must both be MxN. They must
%   also be periodic (ie., pre-processed with a cosine window). The result
%   is an MxN map of responses.
%
%   Inputs and output are all in the Fourier domain.
%
%   See also MAXRESPONSEDSKCF, MAXRESPONSEDEPTHWEIGHTDSKCF,
%   MODELUPDATEDSKCF, LINEAR_CORRELATION, POLYNOMIAL_CORRELATION,
%
%
%   This function has been inserted in the DS-KCF matlab library from the
%   KCF library released by
%
%   Joao F. Henriques, 2014
%   http://www.isr.uc.pt/~henriques/
    N = size(xf,1) * size(xf,2);
    xx = xf(:)' * xf(:) / N;  %squared norm of x
    yy = yf(:)' * yf(:) / N;  %squared norm of y
    %cross-correlation term in Fourier domain
    xyf = xf .* conj(yf);
    xy = sum(real(ifft2(xyf)), 3);  %to spatial domain
    %calculate gaussian response for all positions, then go back to the
    %Fourier domain
    kf = fft2(exp(-1 / sigma^2 * max(0, (xx + yy - 2 * xy) / numel(xf))));
    %whos
    %pause
    %xf
    %yf
    %pause
end