Description of get_subwindow
get_subwindow
PURPOSE
GET_SUBWINDOW
SYNOPSIS
function out = get_subwindow(im, pos, sz)
DESCRIPTION
GET_SUBWINDOW
 GET_SUBWINDOWwith Obtain sub-window from image, replication-padding.
   Returns sub-window of image IM centered at POS ([y, x] coordinates),
   with size SZ ([height, width]). If any pixels are outside of the image,
   they will replicate the values at the borders.
   See also: TARGETSEARCHDSKCF, SINGLEFRAMEDSKCF,
   SINGLEFRAMEDSKCF_OCCLUDER
   This function has been inserted in the DS-KCF matlab library from the
   KCF library released by
   Joao F. Henriques, 2014
   http://www.isr.uc.pt/~henriques/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
targetSearchDSKCF TARGETSEARCHDSKCF function for segmenting the occluding object
singleFrameDSKCF SINGLEFRAMEDSKCF.m is the core function of DS-KCF tracker
singleFrameDSKCF_occluder SINGLEFRAMEDSKCF_OCCLUDER.m functions for tracking occluding object
SOURCE CODE
function out = get_subwindow(im, pos, sz)
%GET_SUBWINDOW
%
% GET_SUBWINDOWwith Obtain sub-window from image, replication-padding.
%   Returns sub-window of image IM centered at POS ([y, x] coordinates),
%   with size SZ ([height, width]). If any pixels are outside of the image,
%   they will replicate the values at the borders.
%
%   See also: TARGETSEARCHDSKCF, SINGLEFRAMEDSKCF,
%   SINGLEFRAMEDSKCF_OCCLUDER
%
%   This function has been inserted in the DS-KCF matlab library from the
%   KCF library released by
%
%   Joao F. Henriques, 2014
%   http://www.isr.uc.pt/~henriques/
%
%
    if isscalar(sz),  %square sub-window
        sz = [sz, sz];
    end
    xs = floor(pos(2)) + (1:sz(2)) - floor(sz(2)/2);
    ys = floor(pos(1)) + (1:sz(1)) - floor(sz(1)/2);
    %check for out-of-bounds coordinates, and set them to the values at
    %the borders
    xs(xs < 1) = 1;
    ys(ys < 1) = 1;
    xs(xs > size(im,2)) = size(im,2);
    ys(ys > size(im,1)) = size(im,1);
    %extract image
    out = im(ys, xs, :);
end