Description of polynomial_correlation
polynomial_correlation
PURPOSE
POLYNOMIAL_CORRELATION Polynomial Kernel at all shifts, i.e. kernel correlation.
SYNOPSIS
function kf = polynomial_correlation(xf, yf, a, b)
DESCRIPTION
POLYNOMIAL_CORRELATION Polynomial Kernel at all shifts, i.e. kernel correlation.
   Evaluates a polynomial kernel with constant A and exponent B, for all
   relative shifts between input images XF and YF, which must both be MxN.
   They must also be periodic (ie., pre-processed with a cosine window).
   The result is an MxN map of responses.
   Inputs and output are all in the Fourier domain.
   See also MAXRESPONSEDSKCF, MAXRESPONSEDEPTHWEIGHTDSKCF,
   MODELUPDATEDSKCF, LINEAR_CORRELATION, GAUSSIAN_CORRELATION,
   This function has been inserted in the DS-KCF matlab library from the
   KCF library released by
   Joao F. Henriques, 2014
   http://www.isr.uc.pt/~henriques/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
maxResponseDSKCF MAXRESPONSEDSKCF function for calculating the DSKCF response
maxResponseDepthWeightDSKCF MAXRESPONSEDEPTHWEIGHTDSKCF function for calculating the DSKCF response %
modelUpdateDSKCF MODELUPDATEDSKCF function for updating the DSKCF model %
SOURCE CODE
function kf = polynomial_correlation(xf, yf, a, b)
%POLYNOMIAL_CORRELATION Polynomial Kernel at all shifts, i.e. kernel correlation.
%   Evaluates a polynomial kernel with constant A and exponent B, for all
%   relative shifts between input images XF and YF, which must both be MxN.
%   They must also be periodic (ie., pre-processed with a cosine window).
%   The result is an MxN map of responses.
%
%   Inputs and output are all in the Fourier domain.
%
%   See also MAXRESPONSEDSKCF, MAXRESPONSEDEPTHWEIGHTDSKCF,
%   MODELUPDATEDSKCF, LINEAR_CORRELATION, GAUSSIAN_CORRELATION,
%
%   This function has been inserted in the DS-KCF matlab library from the
%   KCF library released by
%   Joao F. Henriques, 2014
%   http://www.isr.uc.pt/~henriques/
    %cross-correlation term in Fourier domain
    xyf = xf .* conj(yf);
    xy = sum(real(ifft2(xyf)), 3);  %to spatial domain
    %calculate polynomial response for all positions, then go back to the
    %Fourier domain
    kf = fft2((xy / numel(xf) + a) .^ b);
end