Description of roiFromBB
roiFromBB
PURPOSE
ROIFROMBB.m is a function for extracting roi from images given a bounding box
SYNOPSIS
function imgOUT=roiFromBB(imgIN,bbIn)
DESCRIPTION
 ROIFROMBB.m is a function for extracting roi from images given a bounding box
  ROIFROMBB is a function that extracts image roi from an image given a
  bounding box
   INPUT:
  -imIN input image (can be grayscale, depth or color image)
  -bbIn input bounding box in the format [topLeftY, topLeftX,
   bottomRightY, bottomRightX] read as [rowIndexTopLeft, columnIndexTopLeft,
   rowIndexBottomRight, columnIndexBottomRight]
   OUTPUT
  -imOUT selected ROI
 See also INITDISTRIBUTIONFAST, CHECKOCCLUSIONSDSKCF_NOISEMODEL,
 CHECKOCCLUSIONSDSKCF_SECONDPLANE, OCCLUDINGOBJECTSEGDSKCF,
 SINGLEFRAMEDSKCF,
  University of Bristol
  Massimo Camplani and Sion Hannuna
  massimo.camplani@bristol.ac.uk
  hannuna@compsci.bristol.ac.uk
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
initDistributionFast INITDISTRIBUTIONFAST.m initializes the depth distribution of the DS-KCF tracker
checkOcclusionsDSKCF_noiseModel CHECKOCCLUSIONSDSKCF_NOISEMODEL function for detecting occlusions
checkOcclusionsDSKCF_secondPlane CHECKOCCLUSIONSDSKCF_SECONDPLANE function to detect target candidate in
occludingObjectSegDSKCF OCCLUDINGOBJECTSEGDSKCF function for segmenting the occluding object
singleFrameDSKCF SINGLEFRAMEDSKCF.m is the core function of DS-KCF tracker
SOURCE CODE
% ROIFROMBB.m is a function for extracting roi from images given a bounding box
%
%  ROIFROMBB is a function that extracts image roi from an image given a
%  bounding box
%
%   INPUT:
%  -imIN input image (can be grayscale, depth or color image)
%  -bbIn input bounding box in the format [topLeftY, topLeftX,
%   bottomRightY, bottomRightX] read as [rowIndexTopLeft, columnIndexTopLeft,
%   rowIndexBottomRight, columnIndexBottomRight]
%
%   OUTPUT
%  -imOUT selected ROI
%
% See also INITDISTRIBUTIONFAST, CHECKOCCLUSIONSDSKCF_NOISEMODEL,
% CHECKOCCLUSIONSDSKCF_SECONDPLANE, OCCLUDINGOBJECTSEGDSKCF,
% SINGLEFRAMEDSKCF,
%
%  University of Bristol
%  Massimo Camplani and Sion Hannuna
%
%  massimo.camplani@bristol.ac.uk
%  hannuna@compsci.bristol.ac.uk
function imgOUT=roiFromBB(imgIN,bbIn)
imgOUT=imgIN(bbIn(2):bbIn(4),bbIn(1):bbIn(3),:);
end