Description of calculateNoiseVar
calculateNoiseVar
PURPOSE
CALCULATENOISEVAR.m Calculates the variance of the Kinect Noise
SYNOPSIS
function noiseStd=calculateNoiseVar(depthValue, noiseModelP0, noiseModelP1,noiseModelP2)
DESCRIPTION
 CALCULATENOISEVAR.m Calculates the variance of the Kinect Noise
   CALCULATENOISEVAR is a function for calculating the depth noise for a
   given distance according to the quadratic noise model presented in [1]
   INPUT:
  -depthValue depth measurement
  -noiseModelP0, noiseModelP1,noiseModelP2 noise model parameters
   OUTPUT
  -noiseSTD estimated noise standard deviation
  See also FASTDEPTHSEGMENTATIONDSKCF_NOISEMODEL,
  CHECKOCCLUSIONSDSKCF_NOISEMODEL, CHECKOCCLUSIONSDSKCF_SECONDPLANE
  [1] M. Camplani, T. Mantecon, and L. Salgado. Depth-color fusion
  strategy for 3-D scene modeling with Kinect. Cybernetics, IEEE
  Transactions on, 43(6):1560–1571, 2013
  University of Bristol
  Massimo Camplani and Sion Hannuna
  massimo.camplani@bristol.ac.uk
  hannuna@compsci.bristol.ac.uk
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fastDepthSegmentationDSKCF_noiseModel FASTDEPTHSEGMENTATIONDSKCF_NOISEMODEL.m segments depth data
checkOcclusionsDSKCF_noiseModel CHECKOCCLUSIONSDSKCF_NOISEMODEL function for detecting occlusions
checkOcclusionsDSKCF_secondPlane CHECKOCCLUSIONSDSKCF_SECONDPLANE function to detect target candidate in
SOURCE CODE
function noiseStd=calculateNoiseVar(depthValue,  noiseModelP0, noiseModelP1,noiseModelP2)
% CALCULATENOISEVAR.m Calculates the variance of the Kinect Noise
%
%   CALCULATENOISEVAR is a function for calculating the depth noise for a
%   given distance according to the quadratic noise model presented in [1]
%
%   INPUT:
%  -depthValue depth measurement
%  -noiseModelP0, noiseModelP1,noiseModelP2 noise model parameters
%
%   OUTPUT
%  -noiseSTD estimated noise standard deviation
%
%  See also FASTDEPTHSEGMENTATIONDSKCF_NOISEMODEL,
%  CHECKOCCLUSIONSDSKCF_NOISEMODEL, CHECKOCCLUSIONSDSKCF_SECONDPLANE
%
%  [1] M. Camplani, T. Mantecon, and L. Salgado. Depth-color fusion
%  strategy for 3-D scene modeling with Kinect. Cybernetics, IEEE
%  Transactions on, 43(6):1560–1571, 2013
%
%
%  University of Bristol
%  Massimo Camplani and Sion Hannuna
%
%  massimo.camplani@bristol.ac.uk
%  hannuna@compsci.bristol.ac.uk
noiseStd=noiseModelP0+ noiseModelP1*depthValue+ noiseModelP2*depthValue*depthValue;