Description of zbuffer_cdata
zbuffer_cdata
PURPOSE
ZBUFFER_DATA.m CDATA from hardcopy using zbuffer
SYNOPSIS
function cdata = zbuffer_cdata(hfig)
DESCRIPTION
 ZBUFFER_DATA.m CDATA from hardcopy using zbuffer
 Get CDATA from hardcopy using zbuffer
 Need to have PaperPositionMode be auto
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
manualBBdraw_OCC MANUALBBDRAW_OCC.m produces graphical output for DSKCF tracker
manualBBdraw_OCC_WithLabels MANUALBBDRAW_OCC_WITHLABELS.m function that produces graphical output for DSKCF tracker
manualBBdraw_OCC_WithLabelsVisualize MANUALBBDRAW_OCC_WITHLABELSVISUALIZE.m produces graphical output for DSKCF tracker
SOURCE CODE
function cdata = zbuffer_cdata(hfig)
    % ZBUFFER_DATA.m CDATA from hardcopy using zbuffer
    % Get CDATA from hardcopy using zbuffer
    %
    % Need to have PaperPositionMode be auto
    orig_mode = get(hfig, 'PaperPositionMode');
    set(hfig, 'PaperPositionMode', 'auto');
    cdata = hardcopy(hfig, '-Dzbuffer', '-r0');
    % Restore figure to original state
    set(hfig, 'PaperPositionMode', orig_mode);